# Abilities, by Scrapy_
# 
# All times are minutes BESIDES RegTime, that is in seconds.
Settings:
  GlobalCooldown: 5
  Effects: true
  SpeedAmmount: 1
  SpeedTime: 1
  JumpAmmount: 1
  JumpTime: 1
  StrengthAmmount: 1
  StrengthTime: 1
  AirAmmount: 1
  AirTime: 1
  FireAmmount: 1
  FireTime: 1
  DigAmmount: 1
  DigTime: 1
  RisAmmount: 1
  RisTime: 1
  RegAmmount: 1
  RegTime: 15
  InvTime: 1
  SeeTime: 1
Messages:
  Speed: '&7[&cAbilities&7]: &aYou now have a &b&lSPEED &aeffect activated! '
  Jump: '&7[&cAbilities&7]: &aYou now have a &2&lJUMP &aeffect activated! '
  Strength: '&7[&cAbilities&7]: &aYou now have a &c&lSTRENGTH &aeffect activated! '
  Air: '&7[&cAbilities&7]: &aYou now have a &b&lBREATING &aeffect activated! '
  FireResistance: '&7[&cAbilities&7]: &aYou now have a &4&lFIRE &aeffect activated! '
  Dig: '&7[&cAbilities&7]: &aYou now have a &6&lHASTE &aeffect activated! '
  Resistance: '&7[&cAbilities&7]: &aYou now have a &7&lRESISTANCE &aeffect activated! '
  Regeneration: '&7[&cAbilities&7]: &aYou now have a &d&lREGENERATION &aeffect activated! '
  Invisibility: '&7[&cAbilities&7]: &aYou now have a &f&lINVISIBILITY &aeffect activated! '
  NightVision: '&7[&cAbilities&7]: &aYou now have a &a&lNIGHT VISION &aeffect activated! '
